--维度sql
SELECT C.AGENCY_ID, C.PACKAGE_TYPE, U.CUSTOMER_TYPE, C.CARD_TYPE, V.TYPE 
FROM QTK_CARDINFO C, QTK_CUSTOMERINFO U, QTK_VEHICLEINFO V
WHERE C.CUSTOMER_ID = U.CUSTOMER_ID AND C.VEHICLE_ID = V.VEHICLE_ID
GROUP BY C.AGENCY_ID, C.PACKAGE_TYPE, U.CUSTOMER_TYPE, C.CARD_TYPE, V.TYPE
;

--用户数
SELECT SUBSTR(RESPONSE_STR,INSTR(RESPONSE_STR,'"cardId":')+10,20)
FROM QTK_MONITOR_TRANSINFACE_DETAIL
WHERE SERVICE_TYPE = 'CARDCONFIRM'
AND SUBSTR(RESPONSE_STR,INSTR(RESPONSE_STR,'"message":')+11,2)='成功'
;

--注销数
SELECT SUBSTR(REQUEST_STR,INSTR(REQUEST_STR,'"cardId":')+10,20)
FROM QTK_MONITOR_TRANSINFACE_DETAIL
WHERE SERVICE_TYPE = 'CARDCANCELCONFIRM'
AND SUBSTR(RESPONSE_STR,INSTR(RESPONSE_STR,'"message":')+11,2)='成功'
;

--OBU销售数
SELECT SUBSTR(REQUEST_STR,INSTR(REQUEST_STR,'"obuId":')+9,16)
FROM QTK_MONITOR_TRANSINFACE_DETAIL
WHERE SERVICE_TYPE = 'OBUCONFIRM'
AND SUBSTR(RESPONSE_STR,INSTR(RESPONSE_STR,'"message":')+11,2)='成功'
;

--现存用户量
SELECT COUNT(*) 
FROM QTK_CARDINFO 
WHERE CARD_STATUS != 6
;

--活跃用户数
SELECT * 
FROM QTK_CARDINFO
WHERE CARD_ID IN (
SELECT DISTINCT CARD_ID FROM (
SELECT CARD_ID FROM QTK_FILE_INPROVINCE_DETAIL
UNION 
SELECT CARD_ID FROM QTK_FILE_OUTPROVINCE_DETAIL
UNION
SELECT CARD_ID FROM QTK_FILE_MICROPAYMENT_DETAIL
UNION
SELECT CARD_ID FROM QTK_FILE_MICROPAYMENT_DETAIL
))
;

--通行费金额
SELECT SUM(FEE) 
FROM (
SELECT FEE FROM QTK_FILE_INPROVINCE_DETAIL
UNION 
SELECT FEE FROM QTK_FILE_OUTPROVINCE_DETAIL
UNION
SELECT FEE FROM QTK_TRAFFIC_RECORD_DETAIL WHERE SERIAL_TYPE = 'OUTPROVINCE'
) 
--WHERE CREATE_TIME >= '2019-02-01 00:00:00' AND CREATE_TIME <= '2019-03-01 00:00:00'
;

--单车平均消费金额 : 通行费金额/有消费记录的车辆
SELECT COUNT(DISTINCT V.VEHICLE_ID)
FROM QTK_CARDINFO C, QTK_VEHICLEINFO V
WHERE C.VEHICLE_ID = V.VEHICLE_ID
AND SUBSTR(C.CARD_ID,5,16) IN (
SELECT CARD_ID FROM QTK_FILE_INPROVINCE_DETAIL
UNION 
SELECT CARD_ID FROM QTK_FILE_OUTPROVINCE_DETAIL
UNION
SELECT CARD_ID FROM QTK_TRAFFIC_RECORD_DETAIL WHERE SERIAL_TYPE = 'OUTPROVINCE' 
)
;

--次均消费金额
SELECT SUM(FEE)/COUNT(FEE)
FROM (
SELECT FEE FROM QTK_FILE_INPROVINCE_DETAIL
UNION 
SELECT FEE FROM QTK_FILE_OUTPROVINCE_DETAIL
UNION
SELECT FEE FROM QTK_TRAFFIC_RECORD_DETAIL WHERE SERIAL_TYPE = 'OUTPROVINCE'
) 
;

--充值数 充值金额  
SELECT SUM(RECHARGE_AMOUNT), COUNT(*)
FROM QTK_CHARGE_DETAIL
WHERE CHARGE_ID IN (
SELECT SUBSTR(REQUEST_STR, INSTR(REQUEST_STR,'"chargeId":')+12,36)
FROM QTK_MONITOR_TRANSINFACE_DETAIL
WHERE SERVICE_TYPE = 'CARDCHARGECONFIRM'
AND SUBSTR(RESPONSE_STR,INSTR(RESPONSE_STR,'"message":')+11,2)='成功'
AND CREATE_TIME >= '2018-12-28 00:00:00' AND CREATE_TIME < '2019-03-01 00:00:00'
)
;

--消费数 消费金额 
SELECT SUM(FEE), COUNT(FEE)
FROM (
SELECT FEE FROM QTK_FILE_INPROVINCE_DETAIL
UNION 
SELECT FEE FROM QTK_FILE_OUTPROVINCE_DETAIL
UNION
SELECT FEE FROM QTK_TRAFFIC_RECORD_DETAIL WHERE SERIAL_TYPE = 'OUTPROVINCE'
) 
;

--ETC通行量
SELECT COUNT(FEE)
FROM (
SELECT FEE FROM QTK_FILE_INPROVINCE_DETAIL 
UNION  
SELECT FEE FROM QTK_FILE_OUTPROVINCE_DETAIL 
UNION
SELECT FEE FROM QTK_TRAFFIC_RECORD_DETAIL WHERE SERIAL_TYPE = 'OUTPROVINCE' 
UNION
SELECT FEE FROM QTK_FILE_MICROPAYMENT_DETAIL 
UNION
SELECT RECHARGE_AMOUNT FEE FROM QTK_CHARGE_DETAIL
) 
;

--车籍
SELECT 
SUM (CASE WHEN SUBSTR(RESPONSE_STR,INSTR(RESPONSE_STR,'"vehicleId":')+13,1) = '京' THEN 1 ELSE 0 END) 京,
SUM (CASE WHEN SUBSTR(RESPONSE_STR,INSTR(RESPONSE_STR,'"vehicleId":')+13,1) = '津' THEN 1 ELSE 0 END) 津,
SUM (CASE WHEN SUBSTR(RESPONSE_STR,INSTR(RESPONSE_STR,'"vehicleId":')+13,1) = '冀' THEN 1 ELSE 0 END) 冀,
SUM (CASE WHEN SUBSTR(RESPONSE_STR,INSTR(RESPONSE_STR,'"vehicleId":')+13,1) = '晋' THEN 1 ELSE 0 END) 晋,
SUM (CASE WHEN SUBSTR(RESPONSE_STR,INSTR(RESPONSE_STR,'"vehicleId":')+13,1) = '蒙' THEN 1 ELSE 0 END) 蒙,
SUM (CASE WHEN SUBSTR(RESPONSE_STR,INSTR(RESPONSE_STR,'"vehicleId":')+13,1) = '辽' THEN 1 ELSE 0 END) 辽,
SUM (CASE WHEN SUBSTR(RESPONSE_STR,INSTR(RESPONSE_STR,'"vehicleId":')+13,1) = '吉' THEN 1 ELSE 0 END) 吉,
SUM (CASE WHEN SUBSTR(RESPONSE_STR,INSTR(RESPONSE_STR,'"vehicleId":')+13,1) = '黑' THEN 1 ELSE 0 END) 黑,
SUM (CASE WHEN SUBSTR(RESPONSE_STR,INSTR(RESPONSE_STR,'"vehicleId":')+13,1) = '沪' THEN 1 ELSE 0 END) 沪,
SUM (CASE WHEN SUBSTR(RESPONSE_STR,INSTR(RESPONSE_STR,'"vehicleId":')+13,1) = '苏' THEN 1 ELSE 0 END) 苏,
SUM (CASE WHEN SUBSTR(RESPONSE_STR,INSTR(RESPONSE_STR,'"vehicleId":')+13,1) = '浙' THEN 1 ELSE 0 END) 浙,
SUM (CASE WHEN SUBSTR(RESPONSE_STR,INSTR(RESPONSE_STR,'"vehicleId":')+13,1) = '皖' THEN 1 ELSE 0 END) 皖,
SUM (CASE WHEN SUBSTR(RESPONSE_STR,INSTR(RESPONSE_STR,'"vehicleId":')+13,1) = '闽' THEN 1 ELSE 0 END) 闽,
SUM (CASE WHEN SUBSTR(RESPONSE_STR,INSTR(RESPONSE_STR,'"vehicleId":')+13,1) = '赣' THEN 1 ELSE 0 END) 赣,
SUM (CASE WHEN SUBSTR(RESPONSE_STR,INSTR(RESPONSE_STR,'"vehicleId":')+13,1) = '鲁' THEN 1 ELSE 0 END) 鲁,
SUM (CASE WHEN SUBSTR(RESPONSE_STR,INSTR(RESPONSE_STR,'"vehicleId":')+13,1) = '豫' THEN 1 ELSE 0 END) 豫,
SUM (CASE WHEN SUBSTR(RESPONSE_STR,INSTR(RESPONSE_STR,'"vehicleId":')+13,1) = '鄂' THEN 1 ELSE 0 END) 鄂,
SUM (CASE WHEN SUBSTR(RESPONSE_STR,INSTR(RESPONSE_STR,'"vehicleId":')+13,1) = '湘' THEN 1 ELSE 0 END) 湘,
SUM (CASE WHEN SUBSTR(RESPONSE_STR,INSTR(RESPONSE_STR,'"vehicleId":')+13,1) = '粤' THEN 1 ELSE 0 END) 粤,
SUM (CASE WHEN SUBSTR(RESPONSE_STR,INSTR(RESPONSE_STR,'"vehicleId":')+13,1) = '桂' THEN 1 ELSE 0 END) 桂,
SUM (CASE WHEN SUBSTR(RESPONSE_STR,INSTR(RESPONSE_STR,'"vehicleId":')+13,1) = '渝' THEN 1 ELSE 0 END) 渝,
SUM (CASE WHEN SUBSTR(RESPONSE_STR,INSTR(RESPONSE_STR,'"vehicleId":')+13,1) = '川' THEN 1 ELSE 0 END) 川,
SUM (CASE WHEN SUBSTR(RESPONSE_STR,INSTR(RESPONSE_STR,'"vehicleId":')+13,1) = '贵' THEN 1 ELSE 0 END) 贵,
SUM (CASE WHEN SUBSTR(RESPONSE_STR,INSTR(RESPONSE_STR,'"vehicleId":')+13,1) = '云' THEN 1 ELSE 0 END) 云,
SUM (CASE WHEN SUBSTR(RESPONSE_STR,INSTR(RESPONSE_STR,'"vehicleId":')+13,1) = '陕' THEN 1 ELSE 0 END) 陕,
SUM (CASE WHEN SUBSTR(RESPONSE_STR,INSTR(RESPONSE_STR,'"vehicleId":')+13,1) = '甘' THEN 1 ELSE 0 END) 甘,
SUM (CASE WHEN SUBSTR(RESPONSE_STR,INSTR(RESPONSE_STR,'"vehicleId":')+13,1) = '青' THEN 1 ELSE 0 END) 青,
SUM (CASE WHEN SUBSTR(RESPONSE_STR,INSTR(RESPONSE_STR,'"vehicleId":')+13,1) = '宁' THEN 1 ELSE 0 END) 宁,
SUM (CASE WHEN SUBSTR(RESPONSE_STR,INSTR(RESPONSE_STR,'"vehicleId":')+13,1) = '新' THEN 1 ELSE 0 END) 新
--SUBSTR(RESPONSE_STR,INSTR(RESPONSE_STR,'"vehicleId":')+13,1)
FROM QTK_MONITOR_TRANSINFACE_DETAIL
WHERE SERVICE_TYPE = 'VEHICLEINFOSUBMIT'
AND SUBSTR(RESPONSE_STR,INSTR(RESPONSE_STR,'"message":')+11,2)='成功'
;

--接口交互数
SELECT AGENCY_ID,SERVICE_TYPE, COUNT(*) 
FROM QTK_MONITOR_TRANSINFACE_DETAIL
GROUP BY AGENCY_ID , SERVICE_TYPE
;

--车主年龄
SELECT CUSTOMER_IDNUM, to_char(sysdate, 'yyyy' )-SUBSTR(CUSTOMER_IDNUM,7,4)
FROM QTK_VEHICLEINFO V, QTK_CUSTOMERINFO U
WHERE V.CUSTOMER_ID = U.CUSTOMER_ID 
AND VEHICLE_ID IN (
SELECT SUBSTR(RESPONSE_STR,INSTR(RESPONSE_STR,'"vehicleId":')+13,INSTR(RESPONSE_STR,'"}')-INSTR(RESPONSE_STR,'"vehicleId":')-13)
FROM QTK_MONITOR_TRANSINFACE_DETAIL
WHERE SERVICE_TYPE = 'VEHICLEINFOSUBMIT'
AND SUBSTR(RESPONSE_STR,INSTR(RESPONSE_STR,'"message":')+11,2)='成功'
) AND CUSTOMER_IDTYPE = '101'
;

--工号业务处理量
SELECT STAFF_ID, COUNT(*) 
FROM QTK_MONITOR_TRANSINFACE_DETAIL
GROUP BY STAFF_ID
;

--各工号业务处理量均值
SELECT STAFF_ID, COUNT(*)
FROM QTK_MONITOR_TRANSINFACE_DETAIL
GROUP BY STAFF_ID
;